### ISSUE TITLE
Sandboxing breaks curl

### ISSUE THREAD

**Issue by thatLeaflet** [woutervb/snap-curl#4]
I've had issues where snap curl fails to run due to sandboxing. I tried to install rust and cargo using the offical method, which involves curling the installer and piping that into sh. I've also had this issue while trying to install the Nix package manager.

However, it expects to be able to read and write into /tmp, but cannot due to sandboxing. This is the exact error:
```
evan in ~ > curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh
info: downloading installer
curl: (23) Failure writing output to destination
rustup: command failed: downloader https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init /tmp/tmp.htyjcdJKIT/rustup-init x86_64-unknown-linux-gnu
```

**Comment by woutervb** [comment]
This is known behavior and there is nothing that can be done about this. There doesn't seem to be a category for curl that would allow a version with classic confinement that doesn't have this problem.
