### ISSUE TITLE
Snap version of curl does not work because of permissions

### ISSUE THREAD

**Issue by ahusby** [woutervb/snap-curl#5]
Surprised I don't see this issue here already. As you can see from the comments in Snap Store in Ubuntu 22.04, people have to uninstall the snap version of curl and install the deb package with the apt command instead, in order for all their script and tools to work that rely on curl. Please remove the snap form the Snap Store until this is fixed.

I personally ran into this when I swapped the deb curl with the snap curl which caused [topgrade](https://github.com/r-darwish/topgrade) and [brew](https://brew.sh/) to start failing.

**Comment by woutervb** [comment]
That is known behavior for snaps that aren't installed in classic see #4 & https://forum.snapcraft.io/t/classic-confinement-request-for-curl/24611 for more information
