### ISSUE TITLE
curl from Snap can't create hidden directories; need apt version instead

### ISSUE THREAD

**Issue by lblythen-floss** [woutervb/snap-curl#6]
Hi Wouter,

This was a problem back in December '22, [raised late '21](https://askubuntu.com/questions/1356327/cant-write-to-a-hidden-path-using-curl). I struck it today with a new Ubuntu 22.04.2 install:

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
   https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

Error creating directory /home/lblythen/.vim/autoload.
curl: (23) Failed writing received data to disk/application

Solution reported above is to remove the version of curl installed from Snap and install from apt instead.

Regards,

Lloyd

**Comment by woutervb** [comment]
As mentioned in #2, #4 and #5 this is something that can't be fixed unless the policies around classic confinement change, or and interface is made available. Up until now this hasn't been done by Canonical.

Sorry for the inconvenience
